package com.anhui.fabricbaascommon.constant;

public interface FabricEnvConstant {
    String CORE_VM_ENDPOINT_NAME = "CORE_VM_ENDPOINT";
    String CORE_VM_ENDPOINT = "unix:///host/var/run/docker.sock";
    String CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE_NAME = "CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE";
    String CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE = "byfn";
    String FABRIC_LOGGING_SPEC_NAME = "FABRIC_LOGGING_SPEC";
    String FABRIC_LOGGING_SPEC = "INFO";

    String CORE_PEER_TLS_ENABLED_NAME = "CORE_PEER_TLS_ENABLED";
    String CORE_PEER_TLS_ENABLED = "true";
    String CORE_PEER_GOSSIP_USELEADERELECTION_NAME = "CORE_PEER_GOSSIP_USELEADERELECTION";
    String CORE_PEER_GOSSIP_USELEADERELECTION = "true";
    String CORE_PEER_GOSSIP_ORGLEADER_NAME = "CORE_PEER_GOSSIP_ORGLEADER";
    String CORE_PEER_GOSSIP_ORGLEADER = "false";
    String CORE_PEER_PROFILE_ENABLED_NAME = "CORE_PEER_PROFILE_ENABLED";
    String CORE_PEER_PROFILE_ENABLED = "true";
    String CORE_PEER_TLS_CERT_FILE_NAME = "CORE_PEER_TLS_CERT_FILE";
    String CORE_PEER_TLS_CERT_FILE = "/etc/hyperledger/fabric/tls/server.crt";
    String CORE_PEER_TLS_KEY_FILE_NAME = "CORE_PEER_TLS_KEY_FILE";
    String CORE_PEER_TLS_KEY_FILE = "/etc/hyperledger/fabric/tls/server.key";
    String CORE_PEER_TLS_ROOTCERT_FILE_NAME = "CORE_PEER_TLS_ROOTCERT_FILE";
    String CORE_PEER_TLS_ROOTCERT_FILE = "/etc/hyperledger/fabric/tls/ca.crt";
    String CORE_PEER_ID_NAME = "CORE_PEER_ID";
    String CORE_PEER_ID = "peer0.org1.example.com";
    String CORE_PEER_ADDRESS_NAME = "CORE_PEER_ADDRESS";
    String CORE_PEER_ADDRESS = "peer0.org1.example.com:7051";
    String CORE_PEER_LISTENADDRESS_NAME = "CORE_PEER_LISTENADDRESS";
    String CORE_PEER_LISTENADDRESS = "0.0.0.0:7051";
    String CORE_PEER_CHAINCODEADDRESS_NAME = "CORE_PEER_CHAINCODEADDRESS";
    String CORE_PEER_CHAINCODEADDRESS = "peer0.org1.example.com:7052";
    String CORE_PEER_CHAINCODELISTENADDRESS_NAME = "CORE_PEER_CHAINCODELISTENADDRESS";
    String CORE_PEER_CHAINCODELISTENADDRESS = "0.0.0.0:7052";
    String CORE_PEER_GOSSIP_BOOTSTRAP_NAME = "CORE_PEER_GOSSIP_BOOTSTRAP";
    String CORE_PEER_GOSSIP_BOOTSTRAP = "peer1.org1.example.com:8051";
    String CORE_PEER_GOSSIP_EXTERNALENDPOINT_NAME = "CORE_PEER_GOSSIP_EXTERNALENDPOINT";
    String CORE_PEER_GOSSIP_EXTERNALENDPOINT = "peer0.org1.example.com:7051";
    String CORE_PEER_LOCALMSPID_NAME = "CORE_PEER_LOCALMSPID_NAME";
    String CORE_PEER_LOCALMSPID = "Org1MSP";

    String ORDERER_GENERAL_LISTENADDRESS_NAME = "ORDERER_GENERAL_LISTENADDRESS";
    String ORDERER_GENERAL_LISTENADDRESS = "0.0.0.0";
    String ORDERER_GENERAL_GENESISMETHOD_NAME = "ORDERER_GENERAL_GENESISMETHOD";
    String ORDERER_GENERAL_GENESISMETHOD = "file";
    String ORDERER_GENERAL_GENESISFILE_NAME = "ORDERER_GENERAL_GENESISFILE";
    String ORDERER_GENERAL_GENESISFILE = "/var/hyperledger/orderer/orderer.genesis.block";
    String ORDERER_GENERAL_LOCALMSPID_NAME = "ORDERER_GENERAL_LOCALMSPID";
    String ORDERER_GENERAL_LOCALMSPID = "OrdererMSP";
    String ORDERER_GENERAL_LOCALMSPDIR_NAME = "ORDERER_GENERAL_LOCALMSPDIR";
    String ORDERER_GENERAL_LOCALMSPDIR = "/var/hyperledger/orderer/msp";


    String ORDERER_GENERAL_TLS_ENABLED_NAME = "ORDERER_GENERAL_TLS_ENABLED";
    String ORDERER_GENERAL_TLS_ENABLED = "true";
    String ORDERER_GENERAL_TLS_PRIVATEKEY_NAME = "ORDERER_GENERAL_TLS_PRIVATEKEY";
    String ORDERER_GENERAL_TLS_PRIVATEKEY = "/var/hyperledger/orderer/tls/server.key";
    String ORDERER_GENERAL_TLS_CERTIFICATE_NAME = "ORDERER_GENERAL_TLS_CERTIFICATE";
    String ORDERER_GENERAL_TLS_CERTIFICATE = "/var/hyperledger/orderer/tls/server.crt";
    String ORDERER_GENERAL_TLS_ROOTCAS_NAME = "ORDERER_GENERAL_TLS_ROOTCAS";
    String ORDERER_GENERAL_TLS_ROOTCAS = "[/var/hyperledger/orderer/tls/ca.crt]";


    String ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE_NAME = "ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE";
    String ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE = "/var/hyperledger/orderer/tls/server.crt";
    String ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY_NAME = "ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY";
    String ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY = "/var/hyperledger/orderer/tls/server.key";
    String ORDERER_GENERAL_CLUSTER_ROOTCAS_NAME = "ORDERER_GENERAL_CLUSTER_ROOTCAS";
    String ORDERER_GENERAL_CLUSTER_ROOTCAS = "[/var/hyperledger/orderer/tls/ca.crt]";
}
